"""
executor.py — ACIE Step Executor (v3)
=========================================
Executes a multi-step coding plan generated by the planner.
Each step generates exactly one module, with validation and retry logic.

Key guards:
  - Semantic dedup: checks class/function names, not just raw code string
  - Adaptive over-gen limit: based on step index, not fixed 120 lines
  - Repetition detection via engine._has_repetition
  - Full retry loop (max 2 retries per step) before skipping
"""

import re
from engine import build_prompt, _stream_with_repeat_guard, _has_repetition

# ── Code extraction ───────────────────────────────────────────────────────────

def extract_code(text: str) -> str:
    """Pull code from first fenced block, or return raw text stripped."""
    matches = re.findall(r"```(?:python)?\n(.*?)```", text, re.DOTALL)
    return matches[0].strip() if matches else text.strip()


# ── Semantic dedup helper ─────────────────────────────────────────────────────


# ── Generic names that appear in virtually every class and must NOT be used
# for duplicate detection — otherwise __init__ alone flags every step after
# the first as a duplicate, blocking all subsequent module generation.
_GENERIC_METHOD_NAMES = {
    # Dunder methods
    "__init__", "__str__", "__repr__", "__len__", "__eq__", "__hash__",
    "__call__", "__del__", "__enter__", "__exit__", "__iter__", "__next__",
    # Extremely common single-word method names shared across many classes
    "run", "start", "stop", "reset", "setup", "main",
    "get", "set", "add", "remove", "update", "delete", "clear",
    "save", "load", "read", "write", "close", "open",
    "process", "handle", "execute", "generate", "parse",
}

def _extract_definitions(code: str) -> set:
    """
    Extract meaningful class and function names defined in a code snippet.
    Excludes dunder methods and extremely common generic names (like 'get',
    'add', '__init__') that appear in virtually every class — using those
    for dedup causes false positives and blocks all steps after the first.
    Only class names and domain-specific method names are used for comparison.
    """
    names = set()
    for line in code.splitlines():
        line = line.strip()
        m = re.match(r"^(class|def)\s+(\w+)", line)
        if m:
            name = m.group(2)
            # Skip dunder methods entirely
            if name.startswith("__") and name.endswith("__"):
                continue
            # Skip generic single-word method names shared across all classes
            if name in _GENERIC_METHOD_NAMES:
                continue
            names.add(name)
    return names


def _is_duplicate(code: str, state) -> bool:
    """
    Returns True if the new code redefines a meaningful class or function
    that already exists in a completed module.

    Only class names and domain-specific method names are compared —
    generic names like __init__, get, add are excluded to prevent false
    positives where every class shares common method names.
    """
    new_defs = _extract_definitions(code)

    if not new_defs:
        # No meaningful definitions found — not a duplicate
        # (don't fall back to raw string check: it was causing false positives
        # when code contained class names appearing in comments/docstrings)
        return False

    # Check all existing modules for overlapping meaningful definitions
    for existing_code in state.modules.values():
        existing_defs = _extract_definitions(existing_code)
        overlap = new_defs & existing_defs
        if overlap:
            print(f"   [dedup] overlap detected: {overlap}")
            return True

    return False


# ── Adaptive over-gen limit ───────────────────────────────────────────────────

def _max_lines_for_step(step_index: int, total_steps: int) -> int:
    """
    Later steps (integrators, main runners) legitimately need more lines.
    Earlier steps (single class definitions) should be compact.
    """
    if step_index == total_steps - 1:
        return 300   # last step: main/integration module
    elif step_index >= total_steps - 2:
        return 200   # second-to-last: often CLI or orchestrator
    else:
        return 150   # early steps: single class/module


# ── Main executor ─────────────────────────────────────────────────────────────

def execute_plan_v3(
    model,
    steps:       list,
    user_input:  str,
    memory,
    model_type:  str,
    model_path:  str,
    max_tokens:  int,
    temperature: float,
) -> str:
    from builder  import ProjectState
    from retriever import CodeRetriever

    state     = ProjectState()
    retriever = CodeRetriever(memory)
    total     = len(steps)

    for step in steps:
        state.add_task(step)

    for i, step in enumerate(steps):
        print(f"\n→ Step {i+1}: {step}")

        max_retries  = 2
        retry_count  = 0
        step_success = False

        while retry_count < max_retries:

            context   = state.get_context()
            retrieved = retriever.retrieve(f"{user_input} {step}")

            history = [
                {
                    "role": "system",
                    "content": (
                        "You are building a modular Python project step by step.\n\n"
                        "STRICT RULES (follow exactly):\n"
                        "- Generate ONLY the code for the CURRENT step\n"
                        "- ONE class or module per step — do not write the full project\n"
                        "- Do NOT re-implement or repeat any class/function already shown in existing code\n"
                        "- Do NOT implement steps that come later in the plan\n"
                        "- Do NOT add imports unless they are standard library (os, re, json, datetime, etc.)\n"
                        "- Each class should be self-contained — the final Chatbot step will integrate them\n"
                        "- Output valid Python only — no prose, no file path comments, no instructions\n"
                        "- Start your output directly with the class or function definition\n"
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Project goal: {user_input}\n\n"
                        f"Classes already implemented (DO NOT rewrite these): {state.get_completed_class_names()}\n\n"
                        f"Existing code (do NOT repeat any of this):\n```python\n{context}\n```\n\n"
                        f"CURRENT STEP TO IMPLEMENT NOW (write ONLY this):\n{step}\n\n"
                        f"Output only the Python code for this step. "
                        f"Do not write any other steps. Do not repeat anything from existing code."
                    ),
                },
            ]

            prompt = build_prompt(history, model_type=model_type)
            output = _stream_with_repeat_guard(
                model, prompt,
                max_tokens // 2,
                temperature,
                model_type, model_path,
            )

            code = extract_code(output)

            # ── Validation ────────────────────────────────────────────────────

            if len(code) < 20:
                print(f"⚠ Step {i+1} too short — retrying")
                retry_count += 1
                continue

            if _has_repetition(code):
                print(f"⚠ Step {i+1} repetition detected — retrying")
                retry_count += 1
                continue

            max_lines = _max_lines_for_step(i, total)
            if len(code.splitlines()) > max_lines:
                print(f"⚠ Step {i+1} over-generated ({len(code.splitlines())} lines > {max_lines}) — retrying")
                retry_count += 1
                continue

            if _is_duplicate(code, state):
                print(f"⚠ Step {i+1} duplicate definitions — retrying")
                retry_count += 1
                continue

            # ── Fix 6: DELTA semantic similarity vs previous module ────────
            # Catches near-identical classes that slipped through the name-
            # based dedup (e.g. same class, different variable names).
            if state.modules:
                embedder = getattr(memory, "embedder", None)
                if embedder is not None:
                    try:
                        from delta import _cosine_dist
                        prev_code = list(state.modules.values())[-1]
                        dist = _cosine_dist(
                            embedder.encode(code).astype("float32"),
                            embedder.encode(prev_code).astype("float32"),
                        )
                        if dist < 0.08:
                            print(f"⚠ Step {i+1} semantically identical to previous (dist={dist:.4f}) — retrying")
                            retry_count += 1
                            continue
                    except Exception:
                        pass  # DELTA unavailable — skip check silently

            # ── Success ───────────────────────────────────────────────────────
            safe_name   = re.sub(r"[^a-z0-9_]", "_", step.lower())[:30].strip("_")
            module_name = f"{safe_name}_{i+1}"

            state.add_module(module_name, code)
            state.mark_done(step)
            retriever.add_code(code, module_name)
            step_success = True
            break

        if not step_success:
            print(f"❌ Step {i+1} failed completely — skipping")

    # ── Post-generation validation (3-layer) ──────────────────────────────
    from validator import validate_and_fix
    return validate_and_fix(
        state       = state,
        user_input  = user_input,
        model       = model,
        model_type  = model_type,
        model_path  = model_path,
        max_tokens  = max_tokens,
        temperature = temperature,
    )


# ── Assembly ──────────────────────────────────────────────────────────────────

def assemble_final(state) -> str:
    """Combine all generated modules into one ordered code block."""
    final = "# ===== FULL PROJECT (ACIE v3) =====\n\n"
    for name in state.order:
        code = state.modules[name]
        final += f"\n# FILE: {name}.py\n{code}\n\n"
    return f"```python\n{final}\n```"
