"""
loader.py — Profile-aware model loader
Reads hardware profile from the local profile.json generated by pyinfer.py instead of
re-detecting hardware on every run.
"""

from llama_cpp import Llama
from rich.console import Console

console = Console()


def _get_gpu_layers_from_profile(profile: dict, model_path: str) -> int:
    """
    Look up the best GPU layer count from the profile's pre-computed table,
    matched to the detected model size/quantization.
    """
    vram = profile["hardware"].get("vram_gb", 0)
    opts = profile.get("optimizations", {})
    layer_table = opts.get("gpu_layers_table", {})

    # Detect model key from filename
    name = model_path.lower()
    if "q8" in name and "9b" in name:
        key = "9b-q8"
    elif ("q4" in name or "q4_k" in name) and "9b" in name:
        key = "9b-q4"
    elif "14b" in name:
        key = "14b-q4"
    else:
        key = "7b-q4"

    thresholds = layer_table.get(key, [(8, 40), (4, 24), (0, 0)])
    for threshold, layers in thresholds:
        if vram >= threshold:
            return layers
    return 0


def load_model(model_path: str,
               profile: dict,
               gpu_layers: int  = None,
               context_size: int = None,
               verbose: bool    = False) -> Llama:
    """
    Load a GGUF model using settings derived from the hardware profile.

    Parameters
    ----------
    model_path   : Path to the GGUF file.
    profile      : Full profile dict from setup.load_profile().
    gpu_layers   : Override GPU layers (None = auto from profile).
    context_size : Override context window (None = auto from profile).
    verbose      : Show llama.cpp loading details.
    """
    hw   = profile["hardware"]
    opts = profile["optimizations"]

    # Resolve settings — explicit overrides > profile defaults
    if gpu_layers is None:
        gpu_layers = _get_gpu_layers_from_profile(profile, model_path)

    if context_size is None:
        context_size = opts.get("default_context", 2048)

    batch_size   = opts.get("default_batch", 512)
    cpu_threads  = opts.get("cpu_threads", 4)
    use_mmap     = opts.get("use_mmap", True)
    use_mlock    = opts.get("use_mlock", False)

    # Q8 safety clamp — Q8 layers are much heavier than Q4
    if "q8" in model_path.lower() and gpu_layers > 16 and hw["vram_gb"] < 8:
        gpu_layers = 6
        console.print("[yellow]⚠ Q8 model on low VRAM — clamping GPU layers to 6[/yellow]")

    console.print(f"\n[bold cyan]━━━ Runtime Config (from profile) ━━━[/bold cyan]")
    console.print(f"  Tier      : [bold]{opts.get('tier_label', '?')}[/bold]")
    console.print(f"  GPU       : [green]{hw['gpu_name']}[/green]  ({hw['vram_gb']} GB VRAM)")
    console.print(f"  RAM       : [green]{hw['ram_gb']} GB[/green]")
    console.print(f"  GPU layers: [yellow]{gpu_layers}[/yellow]")
    console.print(f"  Context   : [yellow]{context_size}[/yellow] tokens")
    console.print(f"  Batch     : [yellow]{batch_size}[/yellow]")
    console.print(f"  Threads   : [yellow]{cpu_threads}[/yellow]")
    console.print(f"\n[bold yellow]Loading:[/bold yellow] {model_path}\n")

    model = Llama(
        model_path=model_path,
        n_gpu_layers=gpu_layers,
        n_ctx=context_size,
        n_batch=batch_size,
        n_threads=cpu_threads,
        verbose=verbose,
        use_mmap=use_mmap,
        use_mlock=use_mlock,
    )
    console.print("[bold green]✓ Model loaded![/bold green]\n")
    return model
